### PR TITLE
Bad input plugin crash in grafana 6 #51

### LINKED ISSUE #51: Bad input plugin crash in Grafana 6+
Steps to reproduce:
- create dashboard
- add progress-list panel
- add query with wrong output format

Expected behaviour:
- exclamation mark with error message (as in Grafana 5)

Actual behaviour:
- dashboard crashes

image

### PR DESCRIPTION
**Pull request by jonyrock**
closes #51 #53 

#### bad query
image

#### loading
image

#### no data
image

### CODE REVIEW

File: src/module.ts [hunk 1]
```diff
@@ -62,6 +68,16 @@ class Ctrl extends MetricsPanelCtrl {
   // TODO: change option names or add a tip in editor
   private mappingTypeOptions = ['datapoint to datapoint', 'target to datapoint'];
   private tooltipModeOptions = _.values(TooltipMode);
+  // used to show status messages replacing rendered graphics
+  // see isPanelAlert and panelAlertMessage
+  private _panelAlert = {
+    active: true,
+    // message prop will can bo formatted with html, 
+    message: '<stromng>loading...</strong>' // loading will be showed only once at the beginning
```
Comment (rozetko) [inline src/module.ts:76]:
```suggestion
    message: '<strong>loading...</strong>' // loading will be showed only once at the beginning
```

File: src/module.ts [hunk 2]
```diff
@@ -62,6 +68,16 @@ class Ctrl extends MetricsPanelCtrl {
   // TODO: change option names or add a tip in editor
   private mappingTypeOptions = ['datapoint to datapoint', 'target to datapoint'];
   private tooltipModeOptions = _.values(TooltipMode);
+  // used to show status messages replacing rendered graphics
+  // see isPanelAlert and panelAlertMessage
+  private _panelAlert = {
+    active: true,
+    // message prop will can bo formatted with html,
```
Comment (rozetko) [inline src/module.ts:75]:
```suggestion
    // message prop can be formatted with html, 
```
